### ISSUE TITLE
Fatal error in plugin_init when using also Image Flipper

### ISSUE THREAD

**Issue by Marco-G** [jameskoster/woocommerce-new-product-badge#6]
```
Fatal error: Cannot redeclare plugin_init() 
(previously declared in /.../wp-content/plugins/woocommerce-product-image-flipper/image-flipper.php:27) 
in .../wp-content/plugins/woocommerce-new-product-badge/new-badge.php on line 26
```

**Comment by jameskoster** [comment]
strange, I don't get that error. Is this a standard set up?

**Comment by Marco-G** [comment]
I am on localhost. WP 3.9-beta1-27528. Genesis child theme. A bunch of plugins (mainly yours...).

I switched the sequence of activation but the issue is still there. Very strange.

**Comment by jameskoster** [comment]
Not happening in the current stable. I'll keep my eye on it and address if it still happens in the RC.

**Comment by StaniKub** [comment]
Hey, I have the exact same problem. 

`Fatal error: Cannot redeclare plugin_init() (previously declared in D:\v027502\naplece.sk\WWWRoot\wp-content\plugins\woocommerce-new-product-badge\new-badge.php:26) in D:\v027502\naplece.sk\WWWRoot\wp-content\plugins\woocommerce-product-image-flipper\image-flipper.php on line 25`

Have you found any solutions to this please? Thanks.

**Comment by jameskoster** [comment]
I'll aim to release a fix for this during the week.

**Comment by jameskoster** [comment]
I fixed this in the Product Image Flipper plugin. Running the latest versions of both plugins will resolve the issue.
